# Load zgen
source "${HOME}/Cli/configs/zsh/zgen/zgen.zsh"

# check if there's no init.zsh script
if ! zgen saved; then
    # plugins
    zgen oh-my-zsh
    zgen oh-my-zsh plugins/vi-mode
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/command-not-found
    zgen oh-my-zsh plugins/colored-man-pages
    zgen oh-my-zsh plugins/extract
    zgen load zsh-users/zsh-syntax-highlighting
    # zgen load ytakahashi/igit

    # theme
    zgen load ${HOME}/Cli/configs/zsh/rafa.zsh-theme

    # save all to init script
    zgen save
fi

# Vim style key bindings
bindkey -v
bindkey "fd" vi-cmd-mode

# Forward delete in normal and insert mode
bindkey -a '^[[3~' delete-char
bindkey '^[[3~' delete-char

# Shift tab
bindkey -M menuselect '^[[Z' reverse-menu-complete

# Ctrl + w workaround in Windows.
bindkey "å" backward-kill-word   

# Auto correct
setopt correct

# Switch keyboard layouts when opening a new terminal
#if [ -z "$TMUX" ]; then xdotool keydown Super key space keyup Super; fi

# Don't keep duplicates in zsh history
setopt HIST_IGNORE_ALL_DUPS

# Colors for ls command. https://gist.github.com/thomd/7667642
LS_COLORS="ow=1;34:di=1;34"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

###################################################################

# Use Fuzzy Finder to find files/directories with ctrl+t, command history with
# ctrl+r and fuzzy cd command with alt+c https://github.com/junegunn/fzf 
# Maybe enable this: https://github.com/Aloxaf/fzf-tab
export FZF_COMPLETION_TRIGGER="**"
export FZF_DEFAULT_COMMAND='rg --files --follow --hidden --color=never 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
bindkey "ç" fzf-cd-widget        # Alt+c in Macos.

###################################################################

# export PHP_CS_FIXER_IGNORE_ENV=1

###################################################################

# PATH

# BUILDROOT_BIN="/home/Rafa/Projects/Active/OuterSpaceSounds/projects/mostro/repos/mostro/linux-filesystem/buildroot/output/host/bin/"
# SNAP_BIN="/snap/bin" 
# LOCAL_BIN="${HOME}/.local/bin" 
# COMPOSER_BIN="${HOME}/.config/composer/vendor/bin"
# PIP_BIN="/home/rvg/.local/bin"
export PATH=$PATH:${SNAP_BIN}:${LOCAL_BIN}:${BUILDROOT_BIN}:${COMPOSER_BIN}:${PIP_BIN}

# Training wheels for <alt>-c
# alias cd="echo 'Use <alt>-c instead of cd!' && cd "
# alias cd="echo 'Use <alt>-c instead of cd.'"

# clear 
alias c="clear"

# lf file manager
alias lf1="=lf"
alias lf="tmux-load ~/Cli/configs/lf/tmux-lf.json"

# Alias for cmake in debug and ninja mode
alias cmake_ninja="cmake -G Ninja -DCMAKE_BUILD_TYPE=debug"

# send to trash instead of rm 
alias rm="echo \"Don't use rm, use del.\n\""
alias del=trash

# Force ninja to output colors
export CLICOLOR_FORCE=1

# Alias for gnome-open
# alias open='xdg-open'

# Macos weirdness of open command within tmux.
alias open='reattach-to-user-namespace open'

# Render a markdown file to html, you need to `pacman -S python-grip`
alias md2html='grip -b' # Preview server
alias md2html_export='grip --export' # Actually export a html file

# Set colors for shell
# BASE16_SHELL="~/Cli/zsh/base16-shell/scripts/base16-atelier-forest.sh"
# [[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

# Alias for du (disk usage)
alias du='du -sk (*|.*) | sort -rn | awk "{\$1=\"\"; print \$0}" | xargs du -hs'

# ripgrep use smart case
alias rg="rg -S"

# mv and cp prompt before overwriting
alias mv="mv -i"
alias cp="cp -i"

# Git merge ignoring whitespace
alias gms='git merge -s recursive -Xignore-space-change'

# Git log
alias glg='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit --date=relative'

# Git show log all branches
alias glga='glg --branches'

# Git diff 
alias gd='git difftool'

# Vim diff
alias vimdiff='=nvim -d'

# Directoyr listings
alias ll='ls -alh'
alias l='ls'

# Find hidden files and follow simlinks
function fnd () {
  fd -H -L $1
}

# Tree
alias t='tree -L 2 -C'
alias tt='tree -L 3 -C'
alias ttt='tree -C | less' 

# Vim open on same window
alias vim='echo "Just type v instead of vim"'
alias v='~/Cli/configs/neovim/open-with-neovim.sh'
alias vv='=nvim'

# Use nvim for everything
export EDITOR="nvim"

# Close session easily
alias qq="exit"

# Tmux and tmuxp stuff
export DISABLE_AUTO_TITLE='true'
alias tmux="tmux -2 -u attach || tmux -2 -u new"
alias tmux-save="tmuxp freeze"
alias tmux-load="tmuxp load"

# Do not line wrap when using less
export LESS=-RS

# Tell make to use parallelism for faster builds
export NUMCPUS=10
export MAKEFLAGS="-j$((NUMCPUS))"

# When using pipenv, install dependencies in project dir
# export PIPENV_VENV_IN_PROJECT=1


# PYENV stuff.
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
