#!/bin/sh

# # Disabling this, Better to run similar scripts manually in each repo

# set -e
# PATH="/usr/local/bin:$PATH"
# trap 'rm -f "$$.tags"' EXIT
# git ls-files | \
#   ctags --tag-relative -L - -f"$$.tags" --languages=c --languages=c++
# mv "$$.tags" "tags"
